- id: '1589356162275'
  alias: Tableau TV ouverture
  description: ''
  trigger:
  - entity_id:
    - media_player.living_room_tv
    platform: state
    to: 'on'
    from: 'off'
  condition: []
  action:
  - service: cover.close_cover
    target:
      entity_id:
      - cover.tableau_tv
      device_id: []
      area_id: []
    data: {}
  mode: single
- id: '1589356365410'
  alias: Tableau TV fermeture
  description: ''
  trigger:
  - entity_id: media_player.living_room_tv
    platform: state
    to: 'off'
  condition: []
  action:
  - service: cover.open_cover
    target:
      entity_id:
      - cover.tableau_tv
      device_id: []
      area_id: []
    data: {}
  mode: single
- id: '1601113499442'
  alias: Refresh visual on Plex status
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.plex_plex_for_lg_lg_oled77w7v_z
    from: idle
  - platform: state
    entity_id:
    - media_player.plex_plex_for_lg_lg_oled77w7v_z
    to: idle
  condition: []
  action:
  - service: browser_mod.refresh
    data: {}
  mode: single
- id: '1601189043362'
  alias: Refresh visual on source change
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.living_room_tv_source
  condition: []
  action:
  - service: browser_mod.refresh
    data: {}
  mode: single
- id: '1613936860306'
  alias: Extended Stereo
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.pioneer_avr
    to: 'on'
    for: '10'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: media_player.pioneer_avr
      attribute: source
      state: MEDIA SERVER
    - condition: state
      entity_id: media_player.pioneer_avr
      state: BT AUDIO
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: INTERNET RADIO
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: iPod/USB
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: CD
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: TUNER
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: PHONO
      attribute: source
  action:
  - service: media_player.select_sound_mode
    data:
      sound_mode: EXTENDED STEREO
    entity_id: media_player.pioneer_avr
  mode: single
- id: '1613937031520'
  alias: Auto Surround
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.pioneer_avr
    to: 'on'
    for: '10'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: media_player.pioneer_avr
      attribute: source
      state: BD
    - condition: state
      entity_id: media_player.pioneer_avr
      state: DVD
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: SAT/CBL
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: HDMI 1
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: HDMI 2
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: HDMI 3
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: HDMI 4
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: HDMI 5
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: HDMI 6
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: TV
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: DVR/BDR
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: HDMI 7/MHL
      attribute: source
  action:
  - service: media_player.select_sound_mode
    data:
      sound_mode: AUTO SURROUND
    entity_id: media_player.pioneer_avr
  mode: single
- id: '1624895552291'
  alias: Charlie home start
  description: Set device tracker for Charlie on HA restart
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: device_tracker.see
    data:
      dev_id: pet_charlie
      location_name: "{% if states('binary_sensor.charlie') == 'on' %}\n  home\n{%
        elif states('binary_sensor.charlie') == 'off' %}\n  not_home\n{% else %}\n
        \ unknown\n{% endif %}\n"
  mode: single
  max: 10
- id: '1624895834625'
  alias: Charlie home
  description: Set device tracker for Charlie on binary sensor change
  trigger:
  - platform: state
    entity_id: binary_sensor.charlie
  condition: []
  action:
  - service: device_tracker.see
    data:
      dev_id: pet_charlie
      location_name: "{% if trigger.to_state.state == 'on' %}\n  home\n{% elif trigger.to_state.state
        == 'off' %}\n  not_home\n{% else %}\n   unknown\n{% endif %}\n"
  mode: queued
  max: 10
- id: '1637858673653'
  alias: Store terrasse close button
  description: Close store terrasse on button press
  trigger:
  - device_id: 8615c110ea20420a9ac3e10345415a26
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: top_buttons
  condition: []
  action:
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.store_terrasse_reversed
  mode: single
- id: '1637858821506'
  alias: Store terrasse open button
  description: Open store terrasse on button press
  trigger:
  - device_id: 8615c110ea20420a9ac3e10345415a26
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: bottom_buttons
  condition: []
  action:
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.store_terrasse_reversed
  mode: single
- id: '1644784304855'
  alias: Lovelace update ignore
  description: ''
  trigger:
  - platform: event
    event_type: lovelace_updated
    context: {}
  condition: []
  action:
  - service: browser_mod.notification
    data: {}
  mode: restart
  initial_state: true
- id: '1656948361450'
  alias: HA reboot
  description: ''
  trigger:
  - platform: time
    at: 06:05:00
  condition: []
  action:
  - service: homeassistant.restart
    data: {}
  mode: single
- id: '1681558902386'
  alias: Entrée 10 min.
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.entree
    to: 'on'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.entree
  mode: single
- id: '1683140700552'
  alias: Bathroom 45 min
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.bathroom_door
    - light.bathroom_mirror
    to: 'on'
    for:
      hours: 0
      minutes: 45
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.bathroom_door
      - light.bathroom_mirror
  mode: single
- id: '1684744858875'
  alias: Turn on TV
  description: ''
  trigger:
  - platform: device
    device_id: ef1ffbad0101d9148d85d5469d4cfe76
    domain: webostv
    type: webostv.turn_on
  condition: []
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      broadcast_port: 9
      mac: 7C:64:6C:A8:20:A8
  mode: single
- id: '1699095882288'
  alias: Bathroom sink on with bathroom door
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.bathroom_door
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id:
      - light.bathroom_sink_white
  mode: single
- id: '1699096406867'
  alias: Bathroom sink off with bathroom door
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.bathroom_door
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.bathroom_sink_white
      - light.bathroom_sink
  mode: single
- id: '1705760430224'
  alias: Update bus departures every 3 minutes
  description: ''
  triggers:
  - minutes: /4
    trigger: time_pattern
  conditions: []
  actions:
  - metadata: {}
    data: {}
    target:
      entity_id:
      - sensor.dir_metro_departure
      - sensor.dir_vclb_departure
    action: homeassistant.update_entity
  mode: single
- id: '1730469987335'
  alias: turn_off_avr_music_assistant
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - media_player.sc_lx78
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 1
  conditions:
  - condition: state
    state: 'off'
    entity_id: media_player.living_room_tv
  actions:
  - action: media_player.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: media_player.pioneer_avr
  mode: single
- id: '1733045600218'
  alias: X-Mas morning on
  description: ''
  triggers:
  - trigger: time
    at: 06:00:00
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.noel
  mode: single
- id: '1733045702273'
  alias: X-Mas morning off
  description: ''
  triggers:
  - trigger: sun
    event: sunrise
    offset: 00:30
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.noel
  mode: single
- id: '1733045735507'
  alias: X-mas evening on
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: 0
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.noel
  mode: single
- id: '1733045794336'
  alias: X-mas evening off
  description: ''
  triggers:
  - trigger: time
    at: '22:30:00'
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.noel
  mode: single
- id: '1743361176857'
  alias: amis_lumieres
  description: ''
  use_blueprint:
    path: vandalon/z2m EnOcean PTM 215Z (Friends of Hue) switch.yaml
    input:
      controller: amis_lit
      button_1_pressed: []
      button_2_pressed: []
      button_3_pressed: []
      hold_delay: 500
      button_1_released:
      - action: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.amis_plafonnier
      button_3_released:
      - action: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.amis_prises
- id: '1743770687084'
  alias: carport lights
  description: ''
  triggers:
  - entity_id: binary_sensor.carport_movement_occupancy
    to: 'on'
    trigger: state
  conditions:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      entity_id: light.carport
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 50
    target:
      entity_id: light.carport
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 3
    target:
      entity_id: light.carport
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.carport
  mode: restart
- id: '1743867531123'
  alias: bathroom_movement
  description: ''
  triggers:
  - entity_id:
    - binary_sensor.movement_bathroom_occupancy
    to: 'on'
    trigger: state
  conditions:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
    enabled: true
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 50
    target:
      entity_id: light.bathroom_sink_white
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 15
      transition: 10
    target:
      entity_id: light.bathroom_sink_white
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    metadata: {}
    data:
      transition: 10
    target:
      entity_id: light.bathroom_sink_white
  mode: restart
- id: '1751232584691'
  alias: Interrupteur lit parents
  description: ''
  use_blueprint:
    path: vandalon/z2m EnOcean PTM 215Z (Friends of Hue) switch.yaml
    input:
      controller: Lit parents interrupteur
      button_1_pressed: []
      button_1_released:
      - action: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.chevet_cdrx
      button_3_pressed: []
      button_1_and_3_released:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          device_id: 5de5b3fbe2e6710f1fc8dd059d0bc07c
      button_3_released:
      - action: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.chevet_nanne
      button_1_and_3_held:
      - repeat:
          count: 25
          sequence:
          - action: light.turn_on
            metadata: {}
            data:
              brightness_step: 15
              transition: 1
            target:
              device_id: 5de5b3fbe2e6710f1fc8dd059d0bc07c
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 502
      button_2_and_4_held:
      - repeat:
          count: 25
          sequence:
          - action: light.turn_on
            metadata: {}
            data:
              brightness_step: -15
              transition: 1
            target:
              device_id: 5de5b3fbe2e6710f1fc8dd059d0bc07c
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 500
      button_2_and_4_released:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          device_id: 5de5b3fbe2e6710f1fc8dd059d0bc07c
      button_2_released:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          device_id: 7ed8687e69afcf2a3490fed7d28d1b37
      button_4_released:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          device_id: 7ed8687e69afcf2a3490fed7d28d1b37
      button_4_held:
      - repeat:
          count: 25
          sequence:
          - action: light.turn_on
            metadata: {}
            data:
              transition: 1
              brightness_step: -15
            target:
              device_id: 7ed8687e69afcf2a3490fed7d28d1b37
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 500
      button_2_held:
      - repeat:
          count: 25
          sequence:
          - action: light.turn_on
            metadata: {}
            data:
              transition: 0
              brightness_step: 15
            target:
              device_id: 7ed8687e69afcf2a3490fed7d28d1b37
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 500
      hold_delay: 250
- id: '1751275109320'
  alias: Interrupteur Charles
  description: ''
  use_blueprint:
    path: vandalon/z2m EnOcean PTM 215Z (Friends of Hue) switch.yaml
    input:
      controller: Chambre Charles
      button_1_pressed: []
      button_1_released:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          device_id: 10c772755507623ee95481c572194f8e
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: light.charles_bas_white
      button_3_pressed: []
      button_1_and_3_released: []
      button_3_released:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          device_id: 235f340cfe942150c71f33cd1ce826a8
      button_1_and_3_held: []
      button_2_and_4_held: []
      button_2_and_4_released: []
      button_2_released:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          device_id: 10c772755507623ee95481c572194f8e
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: light.charles_bas_white
      button_4_released:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          device_id: 235f340cfe942150c71f33cd1ce826a8
      button_4_held:
      - repeat:
          count: 25
          sequence:
          - action: light.turn_on
            metadata: {}
            data:
              transition: 1
              brightness_step: -15
            target:
              device_id: 235f340cfe942150c71f33cd1ce826a8
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 500
      button_2_held:
      - repeat:
          count: 25
          sequence:
          - action: light.turn_on
            metadata: {}
            data:
              transition: 1
              brightness_step: -15
            target:
              device_id: 10c772755507623ee95481c572194f8e
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 500
      button_3_held:
      - repeat:
          count: 25
          sequence:
          - action: light.turn_on
            metadata: {}
            data:
              brightness_step: 15
              transition: 1
            target:
              device_id: 235f340cfe942150c71f33cd1ce826a8
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 500
      button_1_held:
      - repeat:
          count: 25
          sequence:
          - action: light.turn_on
            metadata: {}
            data:
              brightness_step: 15
              transition: 1
            target:
              device_id: 10c772755507623ee95481c572194f8e
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 500
      hold_delay: 250
