- id: '1589356162275'
  alias: Tableau TV ouverture
  description: ''
  trigger:
  - entity_id:
    - media_player.living_room_tv
    platform: state
    to: 'on'
    from: 'off'
  condition: []
  action:
  - service: cover.close_cover
    target:
      entity_id:
      - cover.tableau_tv
      device_id: []
      area_id: []
    data: {}
  mode: single
- id: '1589356365410'
  alias: Tableau TV fermeture
  description: ''
  trigger:
  - entity_id: media_player.living_room_tv
    platform: state
    to: 'off'
  condition: []
  action:
  - service: cover.open_cover
    target:
      entity_id:
      - cover.tableau_tv
      device_id: []
      area_id: []
    data: {}
  mode: single
- id: '1601113499442'
  alias: Refresh visual on Plex status
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.plex_plex_for_lg_lg_oled77w7v_z
    from: idle
  - platform: state
    entity_id:
    - media_player.plex_plex_for_lg_lg_oled77w7v_z
    to: idle
  condition: []
  action:
  - service: browser_mod.refresh
    data: {}
  mode: single
- id: '1601189043362'
  alias: Refresh visual on source change
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.living_room_tv_source
  condition: []
  action:
  - service: browser_mod.refresh
    data: {}
  mode: single
- id: '1613936860306'
  alias: Extended Stereo
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.pioneer_avr
    to: 'on'
    for: '10'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: media_player.pioneer_avr
      attribute: source
      state: MEDIA SERVER
    - condition: state
      entity_id: media_player.pioneer_avr
      state: BT AUDIO
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: INTERNET RADIO
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: iPod/USB
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: CD
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: TUNER
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: PHONO
      attribute: source
  action:
  - service: media_player.select_sound_mode
    data:
      sound_mode: EXTENDED STEREO
    entity_id: media_player.pioneer_avr
  mode: single
- id: '1613937031520'
  alias: Auto Surround
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.pioneer_avr
    to: 'on'
    for: '10'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: media_player.pioneer_avr
      attribute: source
      state: BD
    - condition: state
      entity_id: media_player.pioneer_avr
      state: DVD
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: SAT/CBL
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: HDMI 1
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: HDMI 2
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: HDMI 3
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: HDMI 4
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: HDMI 5
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: HDMI 6
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: TV
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: DVR/BDR
      attribute: source
    - condition: state
      entity_id: media_player.pioneer_avr
      state: HDMI 7/MHL
      attribute: source
  action:
  - service: media_player.select_sound_mode
    data:
      sound_mode: AUTO SURROUND
    entity_id: media_player.pioneer_avr
  mode: single
- id: '1624895552291'
  alias: Charlie home start
  description: Set device tracker for Charlie on HA restart
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: device_tracker.see
    data:
      dev_id: pet_charlie
      location_name: "{% if states('binary_sensor.charlie') == 'on' %}\n  home\n{%
        elif states('binary_sensor.charlie') == 'off' %}\n  not_home\n{% else %}\n
        \ unknown\n{% endif %}\n"
  mode: single
  max: 10
- id: '1624895834625'
  alias: Charlie home
  description: Set device tracker for Charlie on binary sensor change
  trigger:
  - platform: state
    entity_id: binary_sensor.charlie
  condition: []
  action:
  - service: device_tracker.see
    data:
      dev_id: pet_charlie
      location_name: "{% if trigger.to_state.state == 'on' %}\n  home\n{% elif trigger.to_state.state
        == 'off' %}\n  not_home\n{% else %}\n   unknown\n{% endif %}\n"
  mode: queued
  max: 10
- id: '1637858673653'
  alias: Store terrasse close button
  description: Close store terrasse on button press
  trigger:
  - device_id: 8615c110ea20420a9ac3e10345415a26
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: top_buttons
  condition: []
  action:
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.store_terrasse_reversed
  mode: single
- id: '1637858821506'
  alias: Store terrasse open button
  description: Open store terrasse on button press
  trigger:
  - device_id: 8615c110ea20420a9ac3e10345415a26
    domain: deconz
    platform: device
    type: remote_button_short_press
    subtype: bottom_buttons
  condition: []
  action:
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.store_terrasse_reversed
  mode: single
- id: '1644784304855'
  alias: Lovelace update ignore
  description: ''
  trigger:
  - platform: event
    event_type: lovelace_updated
    context: {}
  condition: []
  action:
  - service: browser_mod.notification
    data: {}
  mode: restart
  initial_state: true
- id: '1656948361450'
  alias: HA reboot
  description: ''
  trigger:
  - platform: time
    at: 06:05:00
  condition: []
  action:
  - service: homeassistant.restart
    data: {}
  mode: single
- id: '1681558902386'
  alias: Entrée 10 min.
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.entree
    to: 'on'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.entree
  mode: single
- id: '1683140700552'
  alias: Bathroom 45 min
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.bathroom_door
    - light.bathroom_mirror
    to: 'on'
    for:
      hours: 0
      minutes: 45
      seconds: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.bathroom_door
      - light.bathroom_mirror
  mode: single
- id: '1684744858875'
  alias: Turn on TV
  description: ''
  trigger:
  - platform: device
    device_id: ef1ffbad0101d9148d85d5469d4cfe76
    domain: webostv
    type: webostv.turn_on
  condition: []
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      broadcast_port: 9
      mac: 7C:64:6C:A8:20:A8
  mode: single
- id: '1699095882288'
  alias: Bathroom sink on with bathroom door
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.bathroom_door
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id:
      - light.bathroom_sink_white
  mode: single
- id: '1699096406867'
  alias: Bathroom sink off with bathroom door
  description: ''
  trigger:
  - platform: state
    entity_id:
    - light.bathroom_door
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.bathroom_sink_white
      - light.bathroom_sink
  mode: single
- id: '1705760430224'
  alias: Update bus departures every 3 minutes
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /3
  condition: []
  action:
  - service: homeassistant.update_entity
    metadata: {}
    data: {}
    target:
      entity_id:
      - sensor.dir_metro_departure
      - sensor.dir_vclb_departure
  mode: single
- id: '1730469987335'
  alias: turn_off_avr_music_assistant
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - media_player.sc_lx78
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 1
  conditions:
  - condition: state
    state: 'off'
    entity_id: media_player.living_room_tv
  actions:
  - action: media_player.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: media_player.pioneer_avr
  mode: single
- id: '1733045600218'
  alias: X-Mas morning on
  description: ''
  triggers:
  - trigger: time
    at: 06:00:00
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.noel
  mode: single
- id: '1733045702273'
  alias: X-Mas morning off
  description: ''
  triggers:
  - trigger: sun
    event: sunrise
    offset: 00:30
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.noel
  mode: single
- id: '1733045735507'
  alias: X-mas evening on
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: 0
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.noel
  mode: single
- id: '1733045794336'
  alias: X-mas evening off
  description: ''
  triggers:
  - trigger: time
    at: '22:30:00'
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.noel
  mode: single
