title: Home

button_card_templates: !include_dir_merge_named button_templates/

decluttering_templates: !include_dir_merge_named decluttering_templates/

apexcharts_card_templates: !include_dir_merge_named apexcharts_templates/

swipe_nav:
  wrap: true

views:

  #############################################################################################################################################
  #                                                                                                                                           #
  #                                                              Floorplan View                                                               #
  #                                                                                                                                           #
  #############################################################################################################################################

## Ground Floor

- title: Lumières rez
  icon: 'mdi:lightbulb-group'
  panel: true
  badges: []
  path: lights_rez
  cards:
    - type: 'custom:decluttering-card'
      template: simple_grid
      variables:
        - sidebar: !include frontend/sidebar.yaml
        - card: !include frontend/lights_rez.yaml

## First Floor

- title: Lumières 1er
  icon: 'mdi:lightbulb-group'
  panel: true
  badges: []
  path: lights_1er
  cards:
    - type: 'custom:decluttering-card'
      template: simple_grid
      variables:
        - sidebar: !include frontend/sidebar.yaml
        - card: !include frontend/lights_1er.yaml

  #############################################################################################################################################
  #                                                                                                                                           #
  #                                                            Climate View                                                                   #
  #                                                                                                                                           #
  #############################################################################################################################################

## Ground Floor

- title: Climat rez
  icon: 'mdi:water-outline'
  panel: true
  badges: []
  path: climate_rez
  cards:
    - type: 'custom:decluttering-card'
      template: simple_grid
      variables:
        - sidebar: !include frontend/sidebar.yaml
        - card: !include frontend/climate_rez.yaml

 ## First Floor

- title: Climat 1er
  icon: 'mdi:water-outline'
  panel: true
  badges: []
  path: climate_1er
  cards:
    - type: 'custom:decluttering-card'
      template: simple_grid
      variables:
        - sidebar: !include frontend/sidebar.yaml
        - card: !include frontend/climate_1er.yaml

  #############################################################################################################################################
  #                                                                                                                                           #
  #                                                   All Devices (Entities) Classical Style View                                             #
  #                                                                                                                                           #
  #############################################################################################################################################

## Ground Floor

- title: Standard rez
  icon: 'mdi:floor-plan'
  path: all-devices_rez
  panel: true
  cards:
    - type: 'custom:decluttering-card'
      template: simple_grid
      variables:
        - sidebar: !include frontend/sidebar.yaml
        - card: !include frontend/all_rez.yaml

## First Floor

- title: Standard 1er
  icon: 'mdi:floor-plan'
  path: all-devices_1er
  panel: true
  cards:
    - type: 'custom:decluttering-card'
      template: simple_grid
      variables:
        - sidebar: !include frontend/sidebar.yaml
        - card: !include frontend/all_1er.yaml

  #############################################################################################################################################
  #                                                                                                                                           #
  #                                                            Now Playing Media View                                                         #
  #                                                                                                                                           #
  #############################################################################################################################################

- title: Media
  icon: 'mdi:play-circle'
  path: media
  panel: true
  badges: []
  cards:
    - type: 'custom:decluttering-card'
      template: simple_grid
      variables:
        - sidebar: !include frontend/sidebar.yaml
        - card: !include frontend/media.yaml
    
  #############################################################################################################################################
  #                                                                                                                                           #
  #                                                               Weather View                                                                #
  #                                                                                                                                           #
  #############################################################################################################################################

- title: Weather
  icon: 'mdi:weather-pouring'
  path: weather
  panel: true
  badges: []
  cards:
    - type: 'custom:decluttering-card'
      template: simple_grid
      variables:
        - sidebar: !include frontend/sidebar.yaml
        - card: !include frontend/weather.yaml

      
  #############################################################################################################################################
  #                                                                                                                                           #
  #                                                            Systems View                                                                   #
  #                                                                                                                                           #
  #############################################################################################################################################

- title: Systems
  icon: 'mdi:chart-line'
  path: systems
  panel: true
  badges: []
  cards:
    - type: 'custom:decluttering-card'
      template: simple_grid
      variables:
        - sidebar: !include frontend/sidebar.yaml
        - card: !include frontend/systems.yaml