navigation:
  variables:
    navigation: "var_navigation"
    picture: "var_picture"
    top: "var_top"
  tap_action:
    action: navigate
    navigation_path: '[[[ return variables.navigation ]]]'
  hold_action:
    action: none
  show_entity_picture: true
  styles:
    card:
      - background: none
      - box-shadow: none
      - padding: 0
    entity_picture:
      - left: 0%
      - top: 0%
      - width: 100%
      - height: 100%
