- platform: template
  sensors:
    battery_phone_nanne:
      unit_of_measurement: '%'
      value_template: >-
          {% if states('sensor.pixel_8_pro_nanne_battery_level') %}
              {{ states('sensor.pixel_8_pro_nanne_battery_level') | round }}
          {% else %}
              {{ states('sensor.battery_phone_nanne') }}
          {% endif %}
      icon_template: >-
        {% if is_state('sensor.battery_phone_nanne', 'unknown') %}
          mdi:battery-unknown
        {% elif is_state('sensor.pixel_8_pro_nanne_battery_state', 'charging') %}
          mdi:battery-charging
        {% elif states('sensor.pixel_8_pro_nanne_battery_level')|float(default=0) <= 5 %}
          mdi:battery-outline
        {% elif states('sensor.pixel_8_pro_nanne_battery_level')|float(default=0) >= 95 %}
          mdi:battery
        {% else %}
          mdi:battery-{{(states('sensor.pixel_8_pro_nanne_battery_level')|float(default=0) / 10)|round*10}}
        {% endif %}

- platform: template
  sensors:
    battery_phone_cdrx:
      unit_of_measurement: '%'
      value_template: >-
          {% if states('sensor.pixel_8_pro_cdrx_battery_level') %}
              {{ states('sensor.pixel_8_pro_cdrx_battery_level') | round }}
          {% else %}
              {{ states('sensor.battery_phone_cdrx') }}
          {% endif %}
      icon_template: >-
        {% if is_state('sensor.pixel_8_pro_cdrx_attery_state', 'unknown') %}
          mdi:battery-unknown
        {% elif is_state('sensor.pixel_8_pro_cdrx_battery_state', 'charging') %}
          mdi:battery-charging
        {% elif states('sensor.pixel_8_pro_cdrx_battery_level')|float(default=0) <= 5 %}
          mdi:battery-outline
        {% elif states('sensor.pixel_8_pro_cdrx_battery_level')|float(default=0) >= 95 %}
          mdi:battery
        {% else %}
          mdi:battery-{{(states('sensor.pixel_8_pro_cdrx_battery_level')|float(default=0) / 10)|round*10}}
        {% endif %}

- platform: template
  sensors:
    battery_alert:
      value_template: >-
        {{ iif (states('sensor.salon_battery')|float(default=0) < 10 or
          states('sensor.temperature_guest_bathroom_battery_level')|float(default=0) < 10 or
          states('sensor.temperature_entrance_battery_level')|float(default=0) < 10 or
          states('sensor.temperature_guest_battery_level')|float(default=0) < 10 or
          states('sensor.office_battery')|float(default=0) < 10 or
          states('sensor.bathroom_battery')|float(default=0) < 10 or
          states('sensor.temperature_charles_battery_level')|float(default=0) < 10 or
          states('sensor.twins_battery')|float(default=0) < 10 or
          states('sensor.bottom_stairs_battery')|float(default=0) < 10 or
          states('sensor.movement_driveway_battery_level')|float(default=0) < 10 or
          states('sensor.cat_flap_entree_battery_level')|float(default=0) < 10 or
          states('sensor.lenovo_tab_1st_floor_battery')|float(default=0) < 10, 'alert', 'normal') }}
