# - platform: template
#   sensors:
#     trash:
#       value_template: >-
#         {% if states('sensor.poubelle_compost_papier') == 'tomorrow' and states('sensor.verre') != 'tomorrow' %}
#           tomorrow
#         {% elif states('sensor.poubelle_compost_papier') == 'today' and states('sensor.verre') != 'today' %}
#           today
#         {%elif states('sensor.poubelle_compost_papier') == 'tomorrow' and states('sensor.verre') == 'tomorrow' %}
#           verre tomorrow
#         {%elif states('sensor.poubelle_compost_papier') == 'today' and states('sensor.verre') == 'today' %}
#           verre today
#         {% else %}
#           normal
#         {% endif %}

- platform: template
  sensors:
    cat_flap_status:
      friendly_name: "Chatière"
      value_template: >-
        {{ iif (is_state('lock.entree_locked_all', 'locked') or
              is_state('lock.entree_locked_in', 'locked') or
              is_state('lock.entree_locked_out', 'locked'), 'locked', 'unlocked') }}         
      icon_template: >-
        {% if is_state('lock.entree_locked_all', 'locked') %}
          mdi:lock
        {% elif is_state('lock.entree_locked_in', 'locked') %}
          mdi:location-enter
        {% elif is_state('lock.entree_locked_out', 'locked' ) %}
          mdi:location-exit
        {% elif is_state('lock.entree_locked_all', 'unlocked') and
                is_state('lock.entree_locked_in', 'unlocked') and
                is_state('lock.entree_locked_out', 'unlocked') %}
          mdi:lock-open
        {% endif %}

- platform: template
  sensors:
    trash:
      value_template: >-
        {%if (state_attr('calendar.garbage','start_time')|as_timestamp - today_at('00:00')|as_timestamp)/86400 ==1 and (state_attr('calendar.glass','start_time')|as_timestamp - today_at('00:00')|as_timestamp)/86400 !=1 %}
          tomorrow
        {%elif (state_attr('calendar.garbage','start_time')|as_timestamp - today_at('00:00')|as_timestamp)/86400 ==0 and (state_attr('calendar.glass','start_time')|as_timestamp - today_at('00:00')|as_timestamp)/86400 !=0 %}
          today
        {%elif (state_attr('calendar.garbage','start_time')|as_timestamp - today_at('00:00')|as_timestamp)/86400 ==1 and (state_attr('calendar.glass','start_time')|as_timestamp - today_at('00:00')|as_timestamp)/86400 ==1 %}
          verre tomorrow
        {%elif (state_attr('calendar.garbage','start_time')|as_timestamp - today_at('00:00')|as_timestamp)/86400 ==0 and (state_attr('calendar.glass','start_time')|as_timestamp - today_at('00:00')|as_timestamp)/86400 ==0 %}
          verre today
        {% else %}
          normal
        {% endif %}