# - platform: template
#   sensors:
#     cdrxstation1_security_malware:
#       value_template: "{{ state_attr('binary_sensor.cdrxstation1_security_status', 'malware') }}"
#       friendly_name: 'CDRXStation1 malware status'

# - platform: template
#   sensors:
#     cdrxstation1_security_network:
#       value_template: "{{ state_attr('binary_sensor.cdrxstation1_security_status', 'network') }}"
#       friendly_name: 'CDRXStation1 network status'

# - platform: template
#   sensors:
#     cdrxstation1_security_setting:
#       value_template: "{{ state_attr('binary_sensor.cdrxstation1_security_status', 'securitySetting') }}"
#       friendly_name: 'CDRXStation1 security setting status'

# - platform: template
#   sensors:
#     cdrxstation1_security_system_check:
#       value_template: "{{ state_attr('binary_sensor.cdrxstation1_security_status', 'systemCheck') }}"
#       friendly_name: 'CDRXStation1 security system check'

# - platform: template
#   sensors:
#     cdrxstation1_security_user_info:
#       value_template: "{{ state_attr('binary_sensor.cdrxstation1_security_status', 'userInfo') }}"
#       friendly_name: 'CDRXStation1 security user info'

# - platform: template
#   sensors:
#     cdrxstation2_security_malware:
#       value_template: "{{ state_attr('binary_sensor.cdrxstation2_security_status', 'malware') }}"
#       friendly_name: 'CDRXStation2 malware status'

# - platform: template
#   sensors:
#     cdrxstation2_security_network:
#       value_template: "{{ state_attr('binary_sensor.cdrxstation2_security_status', 'network') }}"
#       friendly_name: 'CDRXStation2 network status'

# - platform: template
#   sensors:
#     cdrxstation2_security_setting:
#       value_template: "{{ state_attr('binary_sensor.cdrxstation2_security_status', 'securitySetting') }}"
#       friendly_name: 'CDRXStation2 security setting status'

# - platform: template
#   sensors:
#     cdrxstation2_security_system_check:
#       value_template: "{{ state_attr('binary_sensor.cdrxstation2_security_status', 'systemCheck') }}"
#       friendly_name: 'CDRXStation2 security system check'

# - platform: template
#   sensors:
#     cdrxstation2_security_user_info:
#       value_template: "{{ state_attr('binary_sensor.cdrxstation2_security_status', 'userInfo') }}"
#       friendly_name: 'CDRXStation2 security user info'

- platform: template
  sensors:
    cdrxstation3_security_malware:
      value_template: "{{ state_attr('binary_sensor.cdrxstation3_security_status', 'malware') }}"
      friendly_name: 'CDRXStation3 malware status'

- platform: template
  sensors:
    cdrxstation3_security_network:
      value_template: "{{ state_attr('binary_sensor.cdrxstation3_security_status', 'network') }}"
      friendly_name: 'CDRXStation3 network status'

- platform: template
  sensors:
    cdrxstation3_security_setting:
      value_template: "{{ state_attr('binary_sensor.cdrxstation3_security_status', 'securitySetting') }}"
      friendly_name: 'CDRXStation3 security setting status'

- platform: template
  sensors:
    cdrxstation3_security_system_check:
      value_template: "{{ state_attr('binary_sensor.cdrxstation3_security_status', 'systemCheck') }}"
      friendly_name: 'CDRXStation3 security system check'

- platform: template
  sensors:
    cdrxstation3_security_user_info:
      value_template: "{{ state_attr('binary_sensor.cdrxstation3_security_status', 'userInfo') }}"
      friendly_name: 'CDRXStation3 security user info'

- platform: template
  sensors:
    backupstation_security_malware:
      value_template: "{{ state_attr('binary_sensor.backupstation_security_status', 'malware') }}"
      friendly_name: 'BackupStation malware status'

- platform: template
  sensors:
    backupstation_security_network:
      value_template: "{{ state_attr('binary_sensor.backupstation_security_status', 'network') }}"
      friendly_name: 'BackupStation network status'

- platform: template
  sensors:
    backupstation_security_setting:
      value_template: "{{ state_attr('binary_sensor.backupstation_security_status', 'securitySetting') }}"
      friendly_name: 'BackupStation security setting status'

- platform: template
  sensors:
    backupstation_security_system_check:
      value_template: "{{ state_attr('binary_sensor.backupstation_security_status', 'systemCheck') }}"
      friendly_name: 'BackupStation security system check'

- platform: template
  sensors:
    backupstation_security_user_info:
      value_template: "{{ state_attr('binary_sensor.backupstation_security_status', 'userInfo') }}"
      friendly_name: 'BackupStation security user info'

- platform: template
  sensors:
    cdrxstation3_alert:
      value_template: >-
        {{ iif (states('binary_sensor.cdrxstation3_drive_1_below_min_remaining_life') != 'off' or
          states('binary_sensor.cdrxstation3_drive_1_exceeded_max_bad_sectors') != 'off' or
          states('sensor.cdrxstation3_drive_1_status') != 'normal' or
          states('sensor.cdrxstation3_drive_1_status_smart') != 'normal' or
          states('sensor.cdrxstation3_drive_1_temperature')|float(default=0) > 60 or
          states('binary_sensor.cdrxstation3_drive_2_below_min_remaining_life') != 'off' or
          states('binary_sensor.cdrxstation3_drive_2_exceeded_max_bad_sectors') != 'off' or
          states('sensor.cdrxstation3_drive_2_status') != 'normal' or
          states('sensor.cdrxstation3_drive_2_status_smart') != 'normal' or
          states('sensor.cdrxstation3_drive_2_temperature')|float(default=0) > 60 or
          states('binary_sensor.cdrxstation3_drive_3_below_min_remaining_life') != 'off' or
          states('binary_sensor.cdrxstation3_drive_3_exceeded_max_bad_sectors') != 'off' or
          states('sensor.cdrxstation3_drive_3_status') != 'normal' or
          states('sensor.cdrxstation3_drive_3_status_smart') != 'normal' or
          states('sensor.cdrxstation3_drive_3_temperature')|float(default=0) > 60 or
          states('binary_sensor.cdrxstation3_drive_4_below_min_remaining_life') != 'off' or
          states('binary_sensor.cdrxstation3_drive_4_exceeded_max_bad_sectors') != 'off' or
          states('sensor.cdrxstation3_drive_4_status') != 'normal' or
          states('sensor.cdrxstation3_drive_4_status_smart') != 'normal' or
          states('sensor.cdrxstation3_drive_4_temperature')|float(default=0) > 60 or
          states('binary_sensor.cdrxstation3_drive_1_rx415_1_below_min_remaining_life') != 'off' or
          states('binary_sensor.cdrxstation3_drive_1_rx415_1_exceeded_max_bad_sectors') != 'off' or
          states('sensor.cdrxstation3_drive_1_rx415_1_status') != 'normal' or
          states('sensor.cdrxstation3_drive_1_rx415_1_status_smart') != 'normal' or
          states('sensor.cdrxstation3_drive_1_rx415_1_temperature')|float(default=0) > 60 or
          states('binary_sensor.cdrxstation3_drive_2_rx415_1_below_min_remaining_life') != 'off' or
          states('binary_sensor.cdrxstation3_drive_2_rx415_1_exceeded_max_bad_sectors') != 'off' or
          states('sensor.cdrxstation3_drive_2_rx415_1_status') != 'normal' or
          states('sensor.cdrxstation3_drive_2_rx415_1_status_smart') != 'normal' or
          states('sensor.cdrxstation3_drive_2_rx415_1_temperature')|float(default=0) > 60 or
          states('binary_sensor.cdrxstation3_drive_3_rx415_1_below_min_remaining_life') != 'off' or
          states('binary_sensor.cdrxstation3_drive_3_rx415_1_exceeded_max_bad_sectors') != 'off' or
          states('sensor.cdrxstation3_drive_3_rx415_1_status') != 'normal' or
          states('sensor.cdrxstation3_drive_3_rx415_1_status_smart') != 'normal' or
          states('sensor.cdrxstation3_drive_3_rx415_1_temperature')|float(default=0) > 60 or
          states('binary_sensor.cdrxstation3_drive_4_rx415_1_below_min_remaining_life') != 'off' or
          states('binary_sensor.cdrxstation3_drive_4_rx415_1_exceeded_max_bad_sectors') != 'off' or
          states('sensor.cdrxstation3_drive_4_rx415_1_status') != 'normal' or
          states('sensor.cdrxstation3_drive_4_rx415_1_status_smart') != 'normal' or
          states('sensor.cdrxstation3_drive_4_rx415_1_temperature')|float(default=0) > 60 or
          states('binary_sensor.cdrxstation3_ssd_1_below_min_remaining_life') != 'off' or
          states('binary_sensor.cdrxstation3_ssd_1_exceeded_max_bad_sectors') != 'off' or
          states('sensor.cdrxstation3_ssd_1_status') != 'normal' or
          states('sensor.cdrxstation3_ssd_1_status_smart') != 'normal' or
          states('sensor.cdrxstation3_ssd_1_temperature')|float(default=0) > 60 or
          states('binary_sensor.cdrxstation3_ssd_2_below_min_remaining_life') != 'off' or
          states('binary_sensor.cdrxstation3_ssd_2_exceeded_max_bad_sectors') != 'off' or
          states('sensor.cdrxstation3_ssd_2_status') != 'normal' or
          states('sensor.cdrxstation3_ssd_2_status_smart') != 'normal' or
          states('sensor.cdrxstation3_ssd_2_temperature')|float(default=0) > 60 or
          states('sensor.cdrxstation3_temperature')|float(default=0) > 60 or
          states('sensor.cdrxstation3_volume_1_status') != 'normal' or
          states('sensor.cdrxstation3_volume_1_volume_used')|float(default=0) > 95 or
          states('sensor.cdrxstation3_volume_1_maximum_disk_temp')|float(default=0) > 60, 'alert', 'normal') }}

- platform: template
  sensors:
    backupstation_alert:
      value_template: >-
        {{ iif (states('binary_sensor.backupstation_drive_1_below_min_remaining_life') != 'off' or
          states('binary_sensor.backupstation_drive_1_exceeded_max_bad_sectors') != 'off' or
          states('sensor.backupstation_drive_1_status') != 'normal' or
          states('sensor.backupstation_drive_1_status_smart') != 'normal' or
          states('sensor.backupstation_drive_1_temperature')|float(default=0) > 60 or
          states('binary_sensor.backupstation_drive_2_below_min_remaining_life') != 'off' or
          states('binary_sensor.backupstation_drive_2_exceeded_max_bad_sectors') != 'off' or
          states('sensor.backupstation_drive_2_status') != 'normal' or
          states('sensor.backupstation_drive_2_status_smart') != 'normal' or
          states('sensor.backupstation_drive_2_temperature')|float(default=0) > 60 or
          states('binary_sensor.backupstation_drive_3_below_min_remaining_life') != 'off' or
          states('binary_sensor.backupstation_drive_3_exceeded_max_bad_sectors') != 'off' or
          states('sensor.backupstation_drive_3_status') != 'normal' or
          states('sensor.backupstation_drive_3_status_smart') != 'normal' or
          states('sensor.backupstation_drive_3_temperature')|float(default=0) > 60 or
          states('binary_sensor.backupstation_drive_4_below_min_remaining_life') != 'off' or
          states('binary_sensor.backupstation_drive_4_exceeded_max_bad_sectors') != 'off' or
          states('sensor.backupstation_drive_4_status') != 'normal' or
          states('sensor.backupstation_drive_4_status_smart') != 'normal' or
          states('sensor.backupstation_drive_4_temperature')|float(default=0) > 60 or
          states('binary_sensor.backupstation_drive_1_rx415_1_below_min_remaining_life') != 'off' or
          states('binary_sensor.backupstation_drive_1_rx415_1_exceeded_max_bad_sectors') != 'off' or
          states('sensor.backupstation_drive_1_rx415_1_status') != 'normal' or
          states('sensor.backupstation_drive_1_rx415_1_status_smart') != 'normal' or
          states('sensor.backupstation_drive_1_rx415_1_temperature')|float(default=0) > 60 or
          states('binary_sensor.backupstation_drive_2_rx415_1_below_min_remaining_life') != 'off' or
          states('binary_sensor.backupstation_drive_2_rx415_1_exceeded_max_bad_sectors') != 'off' or
          states('sensor.backupstation_drive_2_rx415_1_status') != 'normal' or
          states('sensor.backupstation_drive_2_rx415_1_status_smart') != 'normal' or
          states('sensor.backupstation_drive_2_rx415_1_temperature')|float(default=0) > 60 or
          states('binary_sensor.backupstation_drive_3_rx415_1_below_min_remaining_life') != 'off' or
          states('binary_sensor.backupstation_drive_3_rx415_1_exceeded_max_bad_sectors') != 'off' or
          states('sensor.backupstation_drive_3_rx415_1_status') != 'normal' or
          states('sensor.backupstation_drive_3_rx415_1_status_smart') != 'normal' or
          states('sensor.backupstation_drive_3_rx415_1_temperature')|float(default=0) > 60 or
          states('binary_sensor.backupstation_drive_4_rx415_1_below_min_remaining_life') != 'off' or
          states('binary_sensor.backupstation_drive_4_rx415_1_exceeded_max_bad_sectors') != 'off' or
          states('sensor.backupstation_drive_4_rx415_1_status') != 'normal' or
          states('sensor.backupstation_drive_4_rx415_1_status_smart') != 'normal' or
          states('sensor.backupstation_drive_4_rx415_1_temperature')|float(default=0) > 60 or
          states('sensor.backupstation_temperature')|float(default=0) > 60 or
          states('sensor.backupstation_volume_1_status') != 'normal' or
          states('sensor.backupstation_volume_1_volume_used')|float(default=0) > 95 or
          states('sensor.backupstation_volume_1_maximum_disk_temp')|float(default=0) > 60, 'alert', 'normal') }}

- platform: template
  sensors:
    cdrxstation_alert:
      value_template: >- 
        {{ iif (states('sensor.cdrxstation3_alert') != 'normal' or
          states('sensor.backupstation_alert') != 'normal', 'alert', 'normal') }}

- platform: template
  sensors:
    cdrxstation_update:
      value_template: >-
        {{ iif (states('update.cdrxstation3_dsm_update') == 'on' or
          states('update.backupstation_dsm_update') == 'on', 'update', 'normal') }}