- platform: template
  sensors:
    depuis_maison_1:
      friendly_name: "Prochain bus"
      icon_template: mdi:bus-alert
      value_template: '{{ as_timestamp(states.sensor.dir_metro_departure.state)| timestamp_custom("%H:%M", True) }}'   

- platform: template
  sensors:
    depuis_maison_2:
      friendly_name: "Bus suivant"
      icon_template: mdi:bus-clock
      value_template: '{{ as_timestamp(states.sensor.lausanne_haute_combe_epalinges_croisettes_departure_1.state)| timestamp_custom("%H:%M", True) }}'

- platform: template
  sensors:
    depuis_maison_3:
      friendly_name: "Bus d'après"
      icon_template: mdi:bus
      value_template: '{{ as_timestamp(states.sensor.lausanne_haute_combe_epalinges_croisettes_departure_2.state)| timestamp_custom("%H:%M", True) }}'

- platform: template
  sensors:
    dir_vclb_1:
      friendly_name: "Prochain bus"
      icon_template: mdi:bus-alert
      value_template: '{{ as_timestamp(states.sensor.dir_vclb_departure.state)| timestamp_custom("%H:%M", True) }}'   

- platform: template
  sensors:
    dir_vclb_2:
      friendly_name: "Bus suivant"
      icon_template: mdi:bus-clock
      value_template: '{{ as_timestamp(states.sensor.lausanne_haute_combe_lausanne_chalet_a_gobet_departure_1.state)| timestamp_custom("%H:%M", True) }}'        

- platform: template
  sensors:
    dir_vclb_3:
      friendly_name: "Bus d'après"
      icon_template: mdi:bus
      value_template: '{{ as_timestamp(states.sensor.lausanne_haute_combe_lausanne_chalet_a_gobet_departure_2.state)| timestamp_custom("%H:%M", True) }}'

# - platform: template
#   sensors:
#     ciboulette_heating_cooling_status:
#       friendly_name: "Chauffage/ventilation"
#       value_template: "{{ states('sensor.ciboulette_parking_heater_heating_ventilation_status') }}"
#       icon_template: >-
#         {% if is_state('sensor.ciboulette_parking_heater_heating_ventilation_status', 'off') %}
#           mdi:radiator-disabled
#         {% elif is_state('sensor.ciboulette_parking_heater_heating_ventilation_status', 'heating') %}
#           mdi:radiator
#         {% elif is_state('sensor.ciboulette_parking_heater_heating_ventilation_status', 'ventilation' ) %}
#           mdi:fan
#         {% endif %}

# - platform: template
#   sensors:
#     ciboulette_parking:
#       friendly_name: "Parquée"
#       value_template: '{{ as_timestamp(states.sensor.ciboulette_parking_time.state)| timestamp_custom("%d.%m.%Y %H:%M", True) }}'

# - platform: template
#   sensors:
#     ciboulette_connected:
#       friendly_name: "Connexion"
#       value_template: '{{ as_timestamp(states.sensor.ciboulette_last_connected.state)| timestamp_custom("%d.%m.%Y %H:%M", True) }}'