version: 4
homeassistant:
  enabled: true
  experimental_event_entities: true
  legacy_action_sensor: true
advanced:
  network_key:
    - 76
    - 122
    - 51
    - 211
    - 45
    - 75
    - 216
    - 119
    - 62
    - 61
    - 51
    - 211
    - 89
    - 28
    - 148
    - 113
  pan_id: 37398
  ext_pan_id:
    - 57
    - 14
    - 146
    - 20
    - 185
    - 19
    - 250
    - 162
  channel: 25
  elapsed: true
  last_seen: ISO_8601
  log_level: info
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt
  password: 4nqWAmHwQYY2dA_L*nf3
  keepalive: 60
  reject_unauthorized: true
  version: 5
serial:
  port: tcp://10.81.19.36:6638
  adapter: zstack
  baudrate: 115200
frontend:
  enabled: true
  port: 8099
groups:
  '1':
    friendly_name: parents_bedroom
  '2':
    friendly_name: twins_bedroom
  '3':
    friendly_name: mezzanine_bedroom
  '4':
    friendly_name: friends_bedroom
  '5':
    friendly_name: upstairs_bathroom
  '6':
    friendly_name: downstairs_bathroom
  '7':
    friendly_name: upstairs_hall
  '8':
    friendly_name: entrance
  '9':
    friendly_name: terrace
  '10':
    friendly_name: kitchen
  '11':
    friendly_name: living_room
  '12':
    friendly_name: dining_room
  '13':
    friendly_name: downstairs_stairs
  '14':
    friendly_name: upstairs_stairs
  '15':
    friendly_name: parking
devices:
  '0x001fee000000727a':
    friendly_name: amis
  '0x000000000175ba48':
    friendly_name: amis_lit
  '0x001fee000000770b':
    friendly_name: entree
  '0x001fee0000006fd3':
    friendly_name: guest_bathroom
  '0x00178801085629ed':
    friendly_name: carport
  '0x0017880106492966':
    friendly_name: carport_movement
  '0x001fee0000006e9e':
    friendly_name: escalier_cave
  '0x001fee00000073a1':
    friendly_name: bathroom
  '0x00212effff00a0a1':
    friendly_name: bathroom_sink
    homeassistant: {}
    optimistic: true
  '0xa4c138e5a9195155':
    friendly_name: movement_bathroom
  '0x001fee00000074ab':
    friendly_name: Jumeaux prises
  '0x00212effff0300f4':
    friendly_name: Jumeaux armoires
  '0x001788010b86ddae':
    friendly_name: Couloir 1
  '0x001788010cc5a455':
    friendly_name: Couloir 2
  '0x001fee0000008c0c':
    friendly_name: Couloir
  '0x680ae2fffe88a7c5':
    friendly_name: Extender parents
  '0x001fee0000002afb':
    friendly_name: Chambre parents
  '0x00212effff0cbf36':
    friendly_name: Plafond parents
  '0x00212effff015520':
    friendly_name: Lit parents
  '0x804b50fffe41d1be':
    friendly_name: Chevet CDRX
  '0x804b50fffe433987':
    friendly_name: Chevet Nanne
  '0x000000000170713a':
    friendly_name: Lit parents interrupteur
  '0x000d6ffffe7c1eee':
    friendly_name: Extender Charles
  '0x00212effff007650':
    friendly_name: Charles bas
  '0x00212effff017bfc':
    friendly_name: Charles haut
  '0x0000000001708a2a':
    friendly_name: Chambre Charles
  '0x00158d0008ce4ab0':
    friendly_name: Office
  '0x00158d0006f91a68':
    friendly_name: Twins
  '0xbc33acfffe5d30c9':
    friendly_name: Bathroom
  '0xbc33acfffe47a6f8':
    friendly_name: Guest bathroom
  '0xbc33acfffe5d310e':
    friendly_name: Entrance
  '0xbc33acfffe5d2fa7':
    friendly_name: Guest
  '0x00158d0007e3b8f0':
    friendly_name: Bottom stairs
  '0x0017880100d21a74':
    friendly_name: Hue spare 1
  '0x0017880100e0b9bf':
    friendly_name: Hue spare 2
  '0x680ae2fffe3fed68':
    friendly_name: Spare switch 2
  '0x385b44fffee76661':
    friendly_name: Spare switch 3
  '0x842e14fffe65c5e3':
    friendly_name: Spare switch 1
  '0x00212effff007572':
    friendly_name: Cuisine deco
  '0x001fee000000584a':
    friendly_name: Cuisine lustre manger
  '0x001fee0000004547':
    friendly_name: Manger plafonnier
  '0x7cb03eaa00ab300c':
    friendly_name: Terrasse sol
  '0x001fee00000026fd':
    friendly_name: Salon plafonnier
  '0x001fee00000052e0':
    friendly_name: Tableau TV
  '0x001fee0000004282':
    friendly_name: Terrasse
  '0xb40ecfd0822e0000':
    friendly_name: Petit totem deco
  '0x00212effff00f294':
    friendly_name: Vinyles
  '0x84b4dbfffe96e892':
    friendly_name: Guirlandes salon
  '0x680ae2fffe41f474':
    friendly_name: Grand totem
  '0xb40ecfd112990000':
    friendly_name: Grand totem deco
  '0x00212effff007534':
    friendly_name: Bar
  '0x000000000170c480':
    friendly_name: Salon interrupteur
  '0x385b44fffee33cd2':
    friendly_name: Panneau lumineux
  '0xbc33acfffe6a0672':
    friendly_name: Petit totem
  '0x00158d0006ed66e0':
    friendly_name: Salon
availability:
  active:
    timeout: 20
  enabled: true
